// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: blmod/v1/blmod.proto

package blmod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleInfo_IconKind int32

const (
	ModuleInfo_ICON_KIND_UNSPECIFIED ModuleInfo_IconKind = 0
	ModuleInfo_ICON_KIND_UTF         ModuleInfo_IconKind = 1
	ModuleInfo_ICON_KIND_PNG         ModuleInfo_IconKind = 2
	ModuleInfo_ICON_KIND_SVG         ModuleInfo_IconKind = 3
)

// Enum value maps for ModuleInfo_IconKind.
var (
	ModuleInfo_IconKind_name = map[int32]string{
		0: "ICON_KIND_UNSPECIFIED",
		1: "ICON_KIND_UTF",
		2: "ICON_KIND_PNG",
		3: "ICON_KIND_SVG",
	}
	ModuleInfo_IconKind_value = map[string]int32{
		"ICON_KIND_UNSPECIFIED": 0,
		"ICON_KIND_UTF":         1,
		"ICON_KIND_PNG":         2,
		"ICON_KIND_SVG":         3,
	}
)

func (x ModuleInfo_IconKind) Enum() *ModuleInfo_IconKind {
	p := new(ModuleInfo_IconKind)
	*p = x
	return p
}

func (x ModuleInfo_IconKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleInfo_IconKind) Descriptor() protoreflect.EnumDescriptor {
	return file_blmod_v1_blmod_proto_enumTypes[0].Descriptor()
}

func (ModuleInfo_IconKind) Type() protoreflect.EnumType {
	return &file_blmod_v1_blmod_proto_enumTypes[0]
}

func (x ModuleInfo_IconKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleInfo_IconKind.Descriptor instead.
func (ModuleInfo_IconKind) EnumDescriptor() ([]byte, []int) {
	return file_blmod_v1_blmod_proto_rawDescGZIP(), []int{0, 0}
}

type ModuleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName      string              `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IconKind         ModuleInfo_IconKind `protobuf:"varint,3,opt,name=icon_kind,json=iconKind,proto3,enum=blmod.v1.ModuleInfo_IconKind" json:"icon_kind,omitempty"`
	IconData         []byte              `protobuf:"bytes,4,opt,name=icon_data,json=iconData,proto3" json:"icon_data,omitempty"`
	ShortDescription string              `protobuf:"bytes,5,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Preamble         string              `protobuf:"bytes,6,opt,name=preamble,proto3" json:"preamble,omitempty"`
}

func (x *ModuleInfo) Reset() {
	*x = ModuleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blmod_v1_blmod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInfo) ProtoMessage() {}

func (x *ModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blmod_v1_blmod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInfo.ProtoReflect.Descriptor instead.
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return file_blmod_v1_blmod_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModuleInfo) GetIconKind() ModuleInfo_IconKind {
	if x != nil {
		return x.IconKind
	}
	return ModuleInfo_ICON_KIND_UNSPECIFIED
}

func (x *ModuleInfo) GetIconData() []byte {
	if x != nil {
		return x.IconData
	}
	return nil
}

func (x *ModuleInfo) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *ModuleInfo) GetPreamble() string {
	if x != nil {
		return x.Preamble
	}
	return ""
}

type AllModulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllModulesRequest) Reset() {
	*x = AllModulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blmod_v1_blmod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllModulesRequest) ProtoMessage() {}

func (x *AllModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blmod_v1_blmod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllModulesRequest.ProtoReflect.Descriptor instead.
func (*AllModulesRequest) Descriptor() ([]byte, []int) {
	return file_blmod_v1_blmod_proto_rawDescGZIP(), []int{1}
}

type AllModulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*ModuleInfo `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *AllModulesResponse) Reset() {
	*x = AllModulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blmod_v1_blmod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllModulesResponse) ProtoMessage() {}

func (x *AllModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blmod_v1_blmod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllModulesResponse.ProtoReflect.Descriptor instead.
func (*AllModulesResponse) Descriptor() ([]byte, []int) {
	return file_blmod_v1_blmod_proto_rawDescGZIP(), []int{2}
}

func (x *AllModulesResponse) GetModules() []*ModuleInfo {
	if x != nil {
		return x.Modules
	}
	return nil
}

type RunModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Header data
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args []byte `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *RunModuleRequest) Reset() {
	*x = RunModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blmod_v1_blmod_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunModuleRequest) ProtoMessage() {}

func (x *RunModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blmod_v1_blmod_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunModuleRequest.ProtoReflect.Descriptor instead.
func (*RunModuleRequest) Descriptor() ([]byte, []int) {
	return file_blmod_v1_blmod_proto_rawDescGZIP(), []int{3}
}

func (x *RunModuleRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunModuleRequest) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type RunModuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RunModuleResponse) Reset() {
	*x = RunModuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blmod_v1_blmod_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunModuleResponse) ProtoMessage() {}

func (x *RunModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blmod_v1_blmod_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunModuleResponse.ProtoReflect.Descriptor instead.
func (*RunModuleResponse) Descriptor() ([]byte, []int) {
	return file_blmod_v1_blmod_proto_rawDescGZIP(), []int{4}
}

func (x *RunModuleResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_blmod_v1_blmod_proto protoreflect.FileDescriptor

var file_blmod_v1_blmod_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x6c, 0x6d, 0x6f, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c, 0x6d, 0x6f, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x6c, 0x6d, 0x6f, 0x64, 0x2e, 0x76, 0x31,
	0x22, 0xc5, 0x02, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x62, 0x6c, 0x6d, 0x6f,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x49, 0x63, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x2b, 0x0a, 0x11, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x22, 0x5e, 0x0a, 0x08, 0x49, 0x63, 0x6f, 0x6e,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x43, 0x4f, 0x4e, 0x5f, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x49, 0x43, 0x4f, 0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x54, 0x46,
	0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x43, 0x4f, 0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x50, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x43, 0x4f, 0x4e, 0x5f, 0x4b, 0x49,
	0x4e, 0x44, 0x5f, 0x53, 0x56, 0x47, 0x10, 0x03, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x6c, 0x6c, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a,
	0x12, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6c, 0x6d, 0x6f, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x10, 0x52, 0x75, 0x6e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x52, 0x75, 0x6e,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0xab, 0x01, 0x0a, 0x12, 0x4c, 0x61, 0x62,
	0x73, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x49, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x2e,
	0x62, 0x6c, 0x6d, 0x6f, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x6c, 0x6d,
	0x6f, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x09, 0x52, 0x75,
	0x6e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x62, 0x6c, 0x6d, 0x6f, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x6c, 0x6d, 0x6f, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x75, 0x6e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1e, 0x5a, 0x1c, 0x62, 0x65, 0x72, 0x74, 0x79, 0x2e,
	0x74, 0x65, 0x63, 0x68, 0x2f, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x62, 0x6c, 0x6d, 0x6f, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blmod_v1_blmod_proto_rawDescOnce sync.Once
	file_blmod_v1_blmod_proto_rawDescData = file_blmod_v1_blmod_proto_rawDesc
)

func file_blmod_v1_blmod_proto_rawDescGZIP() []byte {
	file_blmod_v1_blmod_proto_rawDescOnce.Do(func() {
		file_blmod_v1_blmod_proto_rawDescData = protoimpl.X.CompressGZIP(file_blmod_v1_blmod_proto_rawDescData)
	})
	return file_blmod_v1_blmod_proto_rawDescData
}

var file_blmod_v1_blmod_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blmod_v1_blmod_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_blmod_v1_blmod_proto_goTypes = []interface{}{
	(ModuleInfo_IconKind)(0),   // 0: blmod.v1.ModuleInfo.IconKind
	(*ModuleInfo)(nil),         // 1: blmod.v1.ModuleInfo
	(*AllModulesRequest)(nil),  // 2: blmod.v1.AllModulesRequest
	(*AllModulesResponse)(nil), // 3: blmod.v1.AllModulesResponse
	(*RunModuleRequest)(nil),   // 4: blmod.v1.RunModuleRequest
	(*RunModuleResponse)(nil),  // 5: blmod.v1.RunModuleResponse
}
var file_blmod_v1_blmod_proto_depIdxs = []int32{
	0, // 0: blmod.v1.ModuleInfo.icon_kind:type_name -> blmod.v1.ModuleInfo.IconKind
	1, // 1: blmod.v1.AllModulesResponse.modules:type_name -> blmod.v1.ModuleInfo
	2, // 2: blmod.v1.LabsModulesService.AllModules:input_type -> blmod.v1.AllModulesRequest
	4, // 3: blmod.v1.LabsModulesService.RunModule:input_type -> blmod.v1.RunModuleRequest
	3, // 4: blmod.v1.LabsModulesService.AllModules:output_type -> blmod.v1.AllModulesResponse
	5, // 5: blmod.v1.LabsModulesService.RunModule:output_type -> blmod.v1.RunModuleResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blmod_v1_blmod_proto_init() }
func file_blmod_v1_blmod_proto_init() {
	if File_blmod_v1_blmod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blmod_v1_blmod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blmod_v1_blmod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllModulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blmod_v1_blmod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllModulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blmod_v1_blmod_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blmod_v1_blmod_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunModuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blmod_v1_blmod_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blmod_v1_blmod_proto_goTypes,
		DependencyIndexes: file_blmod_v1_blmod_proto_depIdxs,
		EnumInfos:         file_blmod_v1_blmod_proto_enumTypes,
		MessageInfos:      file_blmod_v1_blmod_proto_msgTypes,
	}.Build()
	File_blmod_v1_blmod_proto = out.File
	file_blmod_v1_blmod_proto_rawDesc = nil
	file_blmod_v1_blmod_proto_goTypes = nil
	file_blmod_v1_blmod_proto_depIdxs = nil
}
