// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: ipfsman/v1/ipfsman.proto

package ipfsman

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoPath string `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
}

func (x *StartNodeRequest) Reset() {
	*x = StartNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipfsman_v1_ipfsman_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNodeRequest) ProtoMessage() {}

func (x *StartNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipfsman_v1_ipfsman_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNodeRequest.ProtoReflect.Descriptor instead.
func (*StartNodeRequest) Descriptor() ([]byte, []int) {
	return file_ipfsman_v1_ipfsman_proto_rawDescGZIP(), []int{0}
}

func (x *StartNodeRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

type StartNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApiMaddrs     []string `protobuf:"bytes,2,rep,name=api_maddrs,json=apiMaddrs,proto3" json:"api_maddrs,omitempty"`
	GatewayMaddrs []string `protobuf:"bytes,3,rep,name=gateway_maddrs,json=gatewayMaddrs,proto3" json:"gateway_maddrs,omitempty"`
}

func (x *StartNodeResponse) Reset() {
	*x = StartNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipfsman_v1_ipfsman_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNodeResponse) ProtoMessage() {}

func (x *StartNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipfsman_v1_ipfsman_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNodeResponse.ProtoReflect.Descriptor instead.
func (*StartNodeResponse) Descriptor() ([]byte, []int) {
	return file_ipfsman_v1_ipfsman_proto_rawDescGZIP(), []int{1}
}

func (x *StartNodeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartNodeResponse) GetApiMaddrs() []string {
	if x != nil {
		return x.ApiMaddrs
	}
	return nil
}

func (x *StartNodeResponse) GetGatewayMaddrs() []string {
	if x != nil {
		return x.GatewayMaddrs
	}
	return nil
}

type StopNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StopNodeRequest) Reset() {
	*x = StopNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipfsman_v1_ipfsman_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNodeRequest) ProtoMessage() {}

func (x *StopNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipfsman_v1_ipfsman_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNodeRequest.ProtoReflect.Descriptor instead.
func (*StopNodeRequest) Descriptor() ([]byte, []int) {
	return file_ipfsman_v1_ipfsman_proto_rawDescGZIP(), []int{2}
}

func (x *StopNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopNodeResponse) Reset() {
	*x = StopNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipfsman_v1_ipfsman_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNodeResponse) ProtoMessage() {}

func (x *StopNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipfsman_v1_ipfsman_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNodeResponse.ProtoReflect.Descriptor instead.
func (*StopNodeResponse) Descriptor() ([]byte, []int) {
	return file_ipfsman_v1_ipfsman_proto_rawDescGZIP(), []int{3}
}

var File_ipfsman_v1_ipfsman_proto protoreflect.FileDescriptor

var file_ipfsman_v1_ipfsman_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x70, 0x66, 0x73, 0x6d, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x70, 0x66,
	0x73, 0x6d, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x70, 0x66, 0x73,
	0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x2f, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65,
	0x70, 0x6f, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x70, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x22, 0x69, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x70, 0x69, 0x5f, 0x6d, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x70, 0x69, 0x4d, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x6d, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4d, 0x61, 0x64, 0x64,
	0x72, 0x73, 0x22, 0x21, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa9, 0x01, 0x0a, 0x12, 0x49, 0x50,
	0x46, 0x53, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4a, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x2e,
	0x69, 0x70, 0x66, 0x73, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x69, 0x70,
	0x66, 0x73, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x08,
	0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6d,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6d, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x62, 0x65, 0x72, 0x74, 0x79, 0x2e, 0x74,
	0x65, 0x63, 0x68, 0x2f, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x69, 0x70, 0x66, 0x73, 0x6d, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipfsman_v1_ipfsman_proto_rawDescOnce sync.Once
	file_ipfsman_v1_ipfsman_proto_rawDescData = file_ipfsman_v1_ipfsman_proto_rawDesc
)

func file_ipfsman_v1_ipfsman_proto_rawDescGZIP() []byte {
	file_ipfsman_v1_ipfsman_proto_rawDescOnce.Do(func() {
		file_ipfsman_v1_ipfsman_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipfsman_v1_ipfsman_proto_rawDescData)
	})
	return file_ipfsman_v1_ipfsman_proto_rawDescData
}

var file_ipfsman_v1_ipfsman_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ipfsman_v1_ipfsman_proto_goTypes = []interface{}{
	(*StartNodeRequest)(nil),  // 0: ipfsman.v1.StartNodeRequest
	(*StartNodeResponse)(nil), // 1: ipfsman.v1.StartNodeResponse
	(*StopNodeRequest)(nil),   // 2: ipfsman.v1.StopNodeRequest
	(*StopNodeResponse)(nil),  // 3: ipfsman.v1.StopNodeResponse
}
var file_ipfsman_v1_ipfsman_proto_depIdxs = []int32{
	0, // 0: ipfsman.v1.IPFSManagerService.StartNode:input_type -> ipfsman.v1.StartNodeRequest
	2, // 1: ipfsman.v1.IPFSManagerService.StopNode:input_type -> ipfsman.v1.StopNodeRequest
	1, // 2: ipfsman.v1.IPFSManagerService.StartNode:output_type -> ipfsman.v1.StartNodeResponse
	3, // 3: ipfsman.v1.IPFSManagerService.StopNode:output_type -> ipfsman.v1.StopNodeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipfsman_v1_ipfsman_proto_init() }
func file_ipfsman_v1_ipfsman_proto_init() {
	if File_ipfsman_v1_ipfsman_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipfsman_v1_ipfsman_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipfsman_v1_ipfsman_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipfsman_v1_ipfsman_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipfsman_v1_ipfsman_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipfsman_v1_ipfsman_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipfsman_v1_ipfsman_proto_goTypes,
		DependencyIndexes: file_ipfsman_v1_ipfsman_proto_depIdxs,
		MessageInfos:      file_ipfsman_v1_ipfsman_proto_msgTypes,
	}.Build()
	File_ipfsman_v1_ipfsman_proto = out.File
	file_ipfsman_v1_ipfsman_proto_rawDesc = nil
	file_ipfsman_v1_ipfsman_proto_goTypes = nil
	file_ipfsman_v1_ipfsman_proto_depIdxs = nil
}
